version: "3"

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5001:5001"
    networks:
      - src_e-commerce-net

  product-service:
    build:
      context: ./product
    networks:
      - src_e-commerce-net

  order-service:
    build:
      context: ./order
    networks:
      - src_e-commerce-net

  rabbitmq:
    build:
      context: ./rabbitmq
    networks:
      - src_e-commerce-net

  # search_filter-service:
  #   build:
  #     context: ./search_filter
  #   networks:
  #     - src_e-commerce-net

  # cart-service:
  #   build:
  #     context: ./cart
  #   networks:
  #     - src_e-commerce-net

  # auth-service:
  #   build:
  #     context: ./user
  #   networks:
  #     - src_e-commerce-net

networks:
  src_e-commerce-net:
    driver: bridge
