FROM rabbitmq:3.8-management-alpine


WORKDIR /usr/src/app

# Copy the rest of your application code
# COPY . .

# Expose the port your service runs on (change this to match your service's port)
EXPOSE 5672 15672
